### ISSUE TITLE
check `options.fileName` directory existence before writing file

### ISSUE THREAD

**Issue by frantic1048** [d4rekanguok/gatsby-plugin-ts#13]
I configured  `options.fileName` under a separate directory in the project root for generated code, and gitignored it.

Then I found a quick failing on CI, errored with: `Error: ENOENT: no such file or directory, open <options.fileName>`.

After minutes I found the error is thrown from `gatsby-plugin-ts` ( https://github.com/d4rekanguok/gatsby-plugin-ts/blob/a31a61c76b237a76dc52274c699e5b9d1f3d97e6/src/graphql-codegen.config.ts#L66 ). 

I think it's a good practice to check directory existence before writing to a *user-defined* pathname. Also, it could be more user-friendly ( ͡° ͜ʖ ͡°).

On the other hand, whitelisting a blank directory for generated code in `.gitigore` is also considerable.

**Comment by d4rekanguok** [comment]
Nice, thank you for reporting in, will fix that 👍

**Comment by d4rekanguok** [comment]
Published in 1.3.1

Please let me know if the problem persists, thanks again for reporting in.

**Comment by frantic1048** [comment]
It works well on 1.3.1, thanks for your quick fix.

---

>>Also, it could be more user-friendly ( ͡° ͜ʖ ͡°).
>
>how can I make it more user-friendly?

Ensuring the directory to write is a point. And I'm exploring more with `gatsby-plugin-ts`. I'd write new issues when I got some ideas.
