### ISSUE TITLE
graphql-toolkit throws error about no type def found since gatsby-plugin-ts 1.3.2

### ISSUE THREAD

**Issue by frantic1048** [d4rekanguok/gatsby-plugin-ts#15]
On `gatsby-plugin-ts` `1.3.0` and `1.3.1`, during building, `graphql-toolkit` only warns with a message like this:

`Unable to find any GraphQL type defintions for the following pointers: <Project Root>/.cache/fragments/*.js`

On `gatsby-plugin-ts@1.3.2`, `graphql-toolkit` throws an error with the above message, which breaks building. I found `1.3.2` is a greenkeeping version, and updated `graphql-toolkit`. Maybe it's caused by graphql-toolkit's internal change.

Related source code: https://github.com/d4rekanguok/gatsby-plugin-ts/blob/4d5e6fae7507c7cfe15b7584fa26aac021352bb7/src/graphql-codegen.config.ts#L26-L29

**Comment by d4rekanguok** [comment]
Thank you again for your attention & patience! And my apologies for breaking your build back-to-back.

I will work on a fix tonight

**Comment by d4rekanguok** [comment]
@frantic1048  I've just released a fix for this in 1.3.3, please let me know if the issue persists

**Comment by frantic1048** [comment]
@d4rekanguok 1.3.3 works nicely~ Your plugin saved my day, thanks for your work ( ͡° ͜ʖ ͡°)
