### ISSUE TITLE
Working example (with a mixed js/ts codebase)?

### ISSUE THREAD

**Issue by mshick** [d4rekanguok/gatsby-plugin-ts#20]
I've been having a bear of a time getting this working in existing projects, so I went back to basics:

1. Install gatsby-starter-default
2. `npm install gatsby-plugin-ts typescript`
3. `tsc --init` and incorporate required settings, as well as `allowJs: true`
4. Add the following to my gatsby-config
```
    {
      options: {
        alwaysCheck: false,
        codegen: true,
        codegenDelay: 250,
        fileName: "./graphql-types.ts",
        tsLoader: {
          logLevel: "warn",
        },
      },
      resolve: `gatsby-plugin-ts`,
    },
```
5. Rename index.js -> index.tsx
5. `npm run build` -> no problems
6. `npm run develop` -> loads of errors:
```
 ERROR #98123  WEBPACK

Generating SSR bundle failed

ERROR in undefined(undefined,undefined):
TS5055: Cannot write file '/my-default-starter/gatsby-browser.js' because it would overwrite input file.


 ERROR #98123  WEBPACK

Generating SSR bundle failed

ERROR in undefined(undefined,undefined):
TS5055: Cannot write file '/my-default-starter/gatsby-config.js' because it would overwrite input file.


 ERROR #98123  WEBPACK

Generating SSR bundle failed

ERROR in undefined(undefined,undefined):
TS5055: Cannot write file '/my-default-starter/gatsby-node.js' because it would overwrite input file.


 ERROR #98123  WEBPACK

Generating SSR bundle failed

ERROR in undefined(undefined,undefined):
TS5055: Cannot write file '/my-default-starter/gatsby-ssr.js' because it would overwrite input file.


 ERROR #98123  WEBPACK

Generating SSR bundle failed

ERROR in undefined(undefined,undefined):
TS5055: Cannot write file '/my-default-starter/public/1-cce43242f980203bd522.js' because it would overwrite input file.
```

and on for all files with a `.js` extension

Are there examples of this plugin working for folks in the wild? It seems that the type checking config is somehow off.

**Comment by d4rekanguok** [comment]
Hi @mshick, I'm sorry to hear that you're having a hard time setting this up, I will follow the steps you shared here to see what went wrong.

I've been using this plugin in a few private repos & converted [the default blog starter](https://github.com/d4rekanguok/gatsby-starter-blog-ts) to use it, however I haven't updated the example for a while so maybe something has changes.

Thank you for making the time to create an issue!

**Comment by d4rekanguok** [comment]
@mshick I've successfully reproduced the error messages you share. So this happens because of mixing `.js` & `.ts` in the codebase. By default tsc transform source files into `.js` files in the same folder they are in. and this causes the errors because  `.js` file can also be a source.

Thankfully the fix is quite simple, if `allowJs` is enabled, an `outDir` should also be specified.

```json
{
  "compilerOptions": {
    "target": "esnext", 
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "jsx": "preserve",
    "moduleResolution": "node",
    "allowJs": true,
    "outDir": "./build"   /* Doesn't have to be a real folder, as it will not be used by ts-loader */
  },
  "include": ["./src"]
}
```

This is a [working example with default starter](https://github.com/d4rekanguok/gatsby-default-starter-ts-example).

I have missed this issue since I haven't tested the plugin with a mixed js/ts codebase - thank you for bringing this up! Please let me know if this indeed fixes your issue.

**Comment by mshick** [comment]
Ah! That's great. Working correctly for me now.

Appreciate the quick response and thanks for the plugin!
