### ISSUE TITLE
Provide an option to disable the typechecker entirely

### ISSUE THREAD

**Issue by mshick** [d4rekanguok/gatsby-plugin-ts#22]
At the very least this would help in debugging. I'm currently experiencing an issue where my preview server running in a docker container is failing, and I believe it's due to the typechecker, but it's quite difficult to debug.

**Comment by d4rekanguok** [comment]
Thank you for the feedback, this is a poor design on my part. I should had exposed a `typeCheck` options that can be turn on & off completely instead of an `alwaysCheck`. Will add this in tonight!

**Comment by mshick** [comment]
Thanks, much appreciated.

As a sidenote, I know you have another issue open where you suggest breaking off the codegen portion. I'll +1 that, as the concerns of typechecking and codegen are related, but not coupled. There's also this plugin https://github.com/DaleLJefferson/gatsby-plugin-typescript-checker that works well, and I could see a typechecker plugin and a codegen plugin each having separate, happy, healthy lives and communities. 

I would PR a breakout of the codegen, but I imagine the plugin naming and packaging is something you'd like to handle yourself.

**Comment by d4rekanguok** [comment]
Published in 2.0.0. Thank you for the nudge on breaking off the codegen portion! I'll try to tackle that tonight. You are right, I should handle the break out myself, but I will gladly accept PR on any other improvement that comes to your mind. Thank you again!

**Comment by d4rekanguok** [comment]
@mshick I've published a new package, [`gatsby-plugin-graphql-codegen`](https://www.npmjs.com/package/gatsby-plugin-graphql-codegen) that contains the codegen portion of the original `gatsby-plugin-ts`, so please try it out if you'd like to only use the codegen feature!

**Comment by mshick** [comment]
Thank you! This is great. Updating my project now...

**Comment by d4rekanguok** [comment]
@mshick Hi Michael, thanks again for the nudge to extract the codegen portion -- the codegen plugin is now many times more popular than the original typescript one!

I wonder if you are still using the plugin & if you have found anything that should be improved.

Thanks again & have a great day!

**Comment by mshick** [comment]
We are! We use it at Parsley Health for the gatsby-generated portions of our site. Been working well. I appreciate your work on this and acting on this request. Cheers!
